from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_view, name='home'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('topic-selection/', views.topic_selection_view, name='topic_selection'),
    path('stance-rating/<int:topic_id>/', views.stance_rating_view, name='stance_rating'),
    path('stance-rating/<int:topic_id>/post/', views.stance_rating_view, {'rating_type': 'post'}, name='stance_rating_post'),
    path('chat/', views.chat_view, name='chat'),
    path('chat/<int:topic_id>/', views.chat_view, name='chat_topic'),
    path('chat/api/message/', views.chat_api_view, name='chat_api'),
    path('chat/api/message/stream/', views.chat_api_stream_view, name='chat_api_stream'),
    path('chat/api/transcribe/', views.transcribe_audio_view,
         name='transcribe_audio'),
    path('chat/api/annotation/', views.annotation_api_view,
         name='annotation_api'),
    path('analysis/<int:topic_id>/', views.analysis_view, name='analysis'),
    path('verify-email/<uuid:token>/',
         views.verify_email_view, name='verify_email'),
    path('password-reset/request/', views.password_reset_request_view,
         name='password_reset_request'),
    path('password-reset/done/', views.password_reset_done_view,
         name='password_reset_done'),
    path('password-reset/<uuid:token>/',
         views.password_reset_confirm_view, name='password_reset_confirm'),
    # Admin views
    path('study-admin/conversations/', views.admin_conversations_view,
         name='admin_conversations'),
    path('study-admin/conversations/<int:user_id>/<str:topic>/',
         views.admin_conversation_detail_view, name='admin_conversation_detail'),
    path('study-admin/analysis/<int:user_id>/<str:topic>/',
         views.admin_analysis_view, name='admin_analysis'),
    path('study-admin/api/llm-suggest-analysis/<int:user_id>/<str:topic>/',
         views.llm_suggest_analysis_view, name='llm_suggest_analysis'),
]
