services:
  web:
    build: .
    volumes:
      - .:/workspace
    ports:
      - "9000:9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ipc: host
    environment:
      - DEBIAN_FRONTEND=noninteractive
      - PYTHONUNBUFFERED=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: ["sh", "-c", "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:9000"]
