"""
Django settings for chatbot_study project.

Generated by 'django-admin startproject' using Django 4.2.29.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'SECRET_KEY', 'django-insecure-5-154cd-x2z9e-)r2jrkkuhqyuwmhvsm=p!3yq%6np8%5%c%fa')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1,.trycloudflare.com').split(',')

# CSRF trusted origins for port forwarding setups (e.g., server->bastion->local, cloudflare tunnels)
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://localhost:8080',
    'http://127.0.0.1:8080',
    'https://*.trycloudflare.com',
] + [origin for origin in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if origin]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'crispy_bootstrap4',
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'chatbot_study.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                            ],
        },
    },
]

WSGI_APPLICATION = 'chatbot_study.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model
AUTH_USER_MODEL = 'accounts.User'

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap4"
CRISPY_TEMPLATE_PACK = "bootstrap4"

# Email Configuration
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = os.getenv('EMAIL_PORT', '587')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@example.com')

# Login URLs
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'chat'
LOGOUT_REDIRECT_URL = 'login'

# ---------------------------------------------------------------------------
# LLM Configuration
# ---------------------------------------------------------------------------
# To swap to a different model or provider, only change values here.
# Application code (views, templates) is fully provider-agnostic.
#
# 'provider'   – dotted import path to any accounts.llm.base.BaseLLM subclass.
# 'model_name' – passed directly to the provider constructor.
# All other keys are forwarded as constructor kwargs to the provider.
#
# Device options: 'cpu' | 'cuda' | 'mps' | 'auto'
# ---------------------------------------------------------------------------

# LLM Provider selection: set LLM_PROVIDER env var to either:
#   - "huggingface"  : Use HuggingFace Transformers (loads model locally)
#   - "vllm"          : Use vLLM server API (model runs on vLLM server, no local model loading)
LLM_PROVIDER = os.getenv("LLM_PROVIDER", "huggingface")

if LLM_PROVIDER == "vllm":
    # vLLM API configuration - model runs on external vLLM server
    # IMPORTANT: When using vLLM, no model is loaded locally, so GPU memory
    # on this machine is not used. Set the vLLM server URL below.
    LLM_CONFIG = {
        "provider": "accounts.llm.vllm.VLLMAPI",
        # The model name should match what's running on the vLLM server
        "model_name": os.getenv("LLM_MODEL_NAME", "Qwen/Qwen3-14QwB"),
        # Base URL of the vLLM server (default assumes it's on localhost)
        "api_base": os.getenv("VLLM_API_BASE", "http://localhost:8090"),
        # Optional API key for vLLM server authentication
        "api_key": os.getenv("VLLM_API_KEY", None),
        # Request timeout in seconds
        "timeout": int(os.getenv("VLLM_TIMEOUT", "120")),
        # Custom system prompt prepended to the model's instructions
        "custom_system_prompt": os.getenv("CUSTOM_SYSTEM_PROMPT", ""),
    }
else:
    # HuggingFace configuration - model is loaded locally (requires GPU memory)
    LLM_CONFIG = {
        "provider": "accounts.llm.huggingface.HuggingFaceLLM",
        "model_name": os.getenv("LLM_MODEL_NAME", "HuggingFaceTB/SmolLM-135M"),
        # Device: 'cpu' | 'cuda' | 'mps' | 'auto'
        # "use_flash_attention_2": False,
        "device": os.getenv("LLM_DEVICE", "cuda"),
        # Torch dtype: 'float32' | 'float16' | 'bfloat16'
        "torch_dtype": os.getenv("LLM_TORCH_DTYPE", "float16"),
        # Quantization: 'bnb_4bit' | 'bnb_8bit' | None
        "quantization": os.getenv("LLM_QUANTIZATION", "bnb_4bit"),
        # Cache directory for downloaded models (stored in workspace for fast loading)
        "cache_dir": os.getenv("LLM_CACHE_DIR", "/workspace/.model_cache"),
        # TurboQuant KV cache compression bits (e.g. 4 for 4-bit compression, or None to disable)
        "turboquant_bits": int(os.getenv("LLM_TURBOQUANT_BITS", "0")) or None,
    }

# OpenRouter Configuration for Admin LLM Suggest Analysis
OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY", "")
OPENROUTER_MODEL = os.getenv("OPENROUTER_MODEL", "anthropic/claude-sonnet-4-5")

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{asctime} {levelname:7s} {name:45s} {message}",
            "style": "{",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "accounts": {
            "handlers": ["console"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
        "transformers": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
