# Generated by Django 4.2.29 on 2026-03-26 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_conversationmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_index', models.IntegerField(help_text='Character offset where the annotation starts')),
                ('end_index', models.IntegerField(help_text='Character offset where the annotation ends')),
                ('selected_text', models.TextField(help_text='The actual text being annotated')),
                ('classification', models.CharField(blank=True, choices=[('good', 'Good'), ('bad', 'Bad')], max_length=20, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='accounts.conversationmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_annotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
