# Generated by Django 5.2.12 on 2026-03-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_message_annotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='IFSMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('note_on_self', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'IFS Meta',
                'verbose_name_plural': 'IFS Meta',
            },
        ),
        migrations.CreateModel(
            name='IFSPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_id', models.CharField(help_text="Unique identifier for the part (e.g., 'perfectionist', 'frightened_child')", max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('protector', 'Protector'), ('exile', 'Exile'), ('healthy_capacity', 'Healthy Capacity'), ('relational_session', 'Relational/Session Process'), ('case_example', 'Case Example')], max_length=30)),
                ('subcategory', models.CharField(blank=True, choices=[('manager', 'Manager'), ('manager_inner_critic', 'Manager - Inner Critic'), ('firefighter', 'Firefighter'), ('exile', 'Exile'), ('healthy_capacity', 'Healthy Capacity'), ('relational_session', 'Relational/Session Process'), ('case_example', 'Case Example')], max_length=30, null=True)),
                ('description', models.TextField()),
                ('positive_intent', models.TextField(blank=True, null=True)),
                ('common_behaviors', models.JSONField(blank=True, default=list)),
                ('often_polarized_with', models.JSONField(blank=True, default=list)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('burden', models.TextField(blank=True, null=True)),
                ('typical_origins', models.TextField(blank=True, null=True)),
                ('common_expressions', models.TextField(blank=True, null=True)),
                ('exile_protected', models.TextField(blank=True, null=True)),
                ('qualities', models.JSONField(blank=True, default=list)),
                ('healthy_version_of', models.CharField(blank=True, max_length=200, null=True)),
                ('transforms', models.CharField(blank=True, max_length=200, null=True)),
                ('role_in_sessions', models.TextField(blank=True, null=True)),
                ('client', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'IFS Part',
                'verbose_name_plural': 'IFS Parts',
                'ordering': ['category', 'subcategory', 'name'],
            },
        ),
    ]
