# Generated by Django 5.2.13 on 2026-04-21 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_ifsmeta_ifspart"),
    ]

    operations = [
        migrations.CreateModel(
            name="StanceRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topic_id",
                    models.IntegerField(
                        help_text="ID of the conversation topic (1-20)"
                    ),
                ),
                ("topic_area", models.CharField(max_length=200)),
                ("specific_question", models.TextField()),
                (
                    "pro_rating",
                    models.IntegerField(
                        choices=[
                            (1, "1 - Strongly Disagree"),
                            (2, "2 - Disagree"),
                            (3, "3 - Neutral"),
                            (4, "4 - Agree"),
                            (5, "5 - Strongly Agree"),
                        ],
                        help_text="Rating for the 'pro' stance",
                    ),
                ),
                (
                    "con_rating",
                    models.IntegerField(
                        choices=[
                            (1, "1 - Strongly Disagree"),
                            (2, "2 - Disagree"),
                            (3, "3 - Neutral"),
                            (4, "4 - Agree"),
                            (5, "5 - Strongly Agree"),
                        ],
                        help_text="Rating for the 'con' stance",
                    ),
                ),
                (
                    "neutral_rating",
                    models.IntegerField(
                        choices=[
                            (1, "1 - Strongly Disagree"),
                            (2, "2 - Disagree"),
                            (3, "3 - Neutral"),
                            (4, "4 - Agree"),
                            (5, "5 - Strongly Agree"),
                        ],
                        help_text="Rating for the 'neutral' stance",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stance_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "topic_id")},
            },
        ),
    ]
