# Generated by Django 5.2.13 on 2026-04-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_add_stance_rating"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="stancerating",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="stancerating",
            name="rating_type",
            field=models.CharField(
                choices=[("pre", "Pre-conversation"), ("post", "Post-conversation")],
                default="pre",
                help_text="Whether this rating was before or after the conversation",
                max_length=10,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stancerating",
            unique_together={("user", "topic_id", "rating_type")},
        ),
    ]
