# Generated by Django 5.2.15 on 2026-06-23 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_stancerating_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="baseline_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="baseline_failed_item_index",
            field=models.IntegerField(
                blank=True,
                help_text="The instrument item index (global battery position) at which the attention check was failed.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="baseline_failed_keystroke",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The key the participant pressed to fail the attention check.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="baseline_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="baseline_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("attention_failed", "Attention Failed"),
                    ("abandoned", "Abandoned"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="InstrumentResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instrument_slug", models.CharField(max_length=50)),
                (
                    "item_index",
                    models.IntegerField(
                        help_text="1-based index of the item within the instrument"
                    ),
                ),
                ("value", models.IntegerField(help_text="The 1-5 response value")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instrument_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["instrument_slug", "item_index"],
                "indexes": [
                    models.Index(
                        fields=["user", "instrument_slug"],
                        name="accounts_in_user_id_907c68_idx",
                    )
                ],
                "unique_together": {("user", "instrument_slug", "item_index")},
            },
        ),
    ]
